# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

# ======================================================== #
# Determines when the action is triggered                  #
# ======================================================== #

on: [push, pull_request]
name: linter

# ======================================================== #
# Determine actions to take                                #
# ======================================================== #

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: Checking out the repository
          uses: actions/checkout@v3

        - name: Setting up R
          uses: r-lib/actions/setup-r@v2
          with:
            use-public-rspm: true

        - name: Installing dependencies
          uses: r-lib/actions/setup-r-dependencies@v2
          with:
            extra-packages: any::lintr, local::.
            needs: lint

        - name: Picking on the coding style
          run: |
            library(lintr)
            excluded_files <- list(
              "inst",
              "data-raw",
              "tests/testthat.R",
              "tests",
              "vignettes-raw",
              "R/RcppExports.R",
              "vignettes/parallel_chains.Rmd",
              "work-docs",
              "vignettes/SMC-Mallows.Rmd" = 19
            )
            style_rules <- list(
              absolute_path_linter(), assignment_linter(), brace_linter(),
              commas_linter(), commented_code_linter(),
              equals_na_linter(), function_left_parentheses_linter(),
              infix_spaces_linter(), whitespace_linter(),
              nonportable_path_linter(),
              pipe_continuation_linter(), seq_linter(), quotes_linter(),
              spaces_inside_linter(), spaces_left_parentheses_linter(),
              T_and_F_symbol_linter(), todo_comment_linter(),
              trailing_blank_lines_linter(), trailing_whitespace_linter(),
              undesirable_function_linter(),
              unnecessary_concatenation_linter()
            )
            lint_package(linters = style_rules, exclusions = excluded_files)
          shell: Rscript {0}
          env:
            LINTR_ERROR_ON_LINT: true
